// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhphpakowivghpisdnzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocGhwYWtvd2l2Z2hwaXNkbnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MDMzMzcsImV4cCI6MjA3MDI3OTMzN30.jNpy6YH1HPgMvHVIIY49difN7FfDAW31umqq3BVP00Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});